export const TalentRequestInfo = [
  {
    title: "1XCNMD",
    name: "Flora Miles1",
    button: "requested",
    number: "+49 5532 5353 98",
    email: "floramiles@gmail.com",
    occupation: "UI Designer",
    place: "Google Inc.",
    experience: "6 years experience",
    date: "5th March 2022",
  },
  {
    title: "1XCNMD",
    name: "Flora Miles2",
    button: "requested",
    number: "+49 5532 5353 98",
    email: "floramiles@gmail.com",
    occupation: "UI Designer",
    place: "Google Inc.",
    experience: "6 years experience",
    date: "5th March 2022",
  },
  {
    title: "1XCNMD",
    name: "Flora Miles3",
    button: "requested",
    number: "+49 5532 5353 98",
    email: "floramiles@gmail.com",
    occupation: "UI Designer",
    place: "Google Inc.",
    experience: "6 years experience",
    date: "5th March 2022",
  },
  {
    title: "1XCNMD",
    name: "Flora Miles4",
    button: "requested",
    number: "+49 5532 5353 98",
    email: "floramiles@gmail.com",
    occupation: "UI Designer",
    place: "Google Inc.",
    experience: "6 years experience",
    date: "5th March 2022",
  },
  {
    title: "1XCNMD",
    name: "Flora Miles5",
    button: "requested",
    number: "+49 5532 5353 98",
    email: "floramiles@gmail.com",
    occupation: "UI Designer",
    place: "Google Inc.",
    experience: "6 years experience",
    date: "5th March 2022",
  },
  {
    title: "1XCNMD",
    name: "Flora6",
    button: "requested",
    number: "+49 5532 5353 98",
    email: "floramiles@gmail.com",
    occupation: "Product Designer",
    place: "Google Inc.",
    experience: "6 years experience",
    date: "5th March 2022",
  },
  {
    title: "1XCNMD",
    name: "Flora Miles7",
    button: "requested",
    number: "+49 5532 5353 98",
    email: "floramiles@gmail.com",
    occupation: "UI Designer",
    place: "Google Inc.",
    experience: "6 years experience",
    date: "5th March 2022",
  },
  {
    title: "1XCNMD",
    name: "Flora Miles8",
    button: "requested",
    number: "+49 5532 5353 98",
    email: "floramiles@gmail.com",
    occupation: "UI Designer",
    place: "Google Inc.",
    experience: "6 years experience",
    date: "5th March 2022",
  },
  {
    title: "1XCNMD",
    name: "Flora Miles9",
    button: "requested",
    number: "+49 5532 5353 98",
    email: "floramiles@gmail.com",
    occupation: "UI Designer",
    place: "Google Inc.",
    experience: "6 years experience",
    date: "5th March 2022",
  },
  {
    title: "1XCNMD",
    name: "Flora Miles10",
    button: "requested",
    number: "+49 5532 5353 98",
    email: "floramiles@gmail.com",
    occupation: "UI Designer",
    place: "Google Inc.",
    experience: "6 years experience",
    date: "5th March 2022",
  },
];
